Repository konstellation-io/kdl, pull requests merged in 2021-02, with the labels that each got.

#160 feat: Open new admin-ui
  kdl-client/electron/main.ts
  kdl-client/src/App.tsx
  kdl-client/src/Components/TitleBar/menu.ts
  kdl-client/src/Pages/Servers/components/Server/Server.tsx
Labels: desktop-app

#163 fix: Update graphql endpoint url
  kdl-client/mock-server/src/index.js
  kdl-client/src/Pages/Server/ServerClient.tsx
Labels: admin-api

#175 fix: load our custom CA in order to get the server config.json correctly
  kdl-client/electron/remote_server_actions.ts
  kdl-client/package.json
  kdl-client/yarn.lock
Labels: bug, desktop-app
